services:
  postgres:
    image: postgres:15
    container_name: ny_taxi_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ny_taxi"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ny_taxi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nicoc2002@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "9000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  mage:
    image: mageai/mageai
    container_name: ny_taxi_mage
    volumes:
      - ./data-orquestador:/home/src
    ports:
      - "6789:6789"
    environment:
      DATABASE_CONNECTION_URL: postgresql+psycopg2://root:root@postgres:5432/ny_taxi
    command: mage start orquestador
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-volume:
  pgadmin-data: